// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobufMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protobufMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protobufMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protobufMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protobufMessage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_protobufMessage_2eproto;
class RouterProtobufMessage;
struct RouterProtobufMessageDefaultTypeInternal;
extern RouterProtobufMessageDefaultTypeInternal _RouterProtobufMessage_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::RouterProtobufMessage* Arena::CreateMaybeMessage<::RouterProtobufMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum RouterMethods : int {
  ROUTER_METHODS_OCPP201 = 0,
  ROUTER_METHODS_WRITE_DATABASE = 1,
  ROUTER_METHODS_READ_DATABASE = 2,
  ROUTER_METHODS_NOTIFY_REALTIME_DATA = 3,
  ROUTER_METHODS_GET_REALTIME_DATA = 4,
  ROUTER_METHODS_NETWORK_ONLINE = 5,
  ROUTER_METHODS_NETWORK_OFFLINE = 6,
  RouterMethods_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  RouterMethods_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool RouterMethods_IsValid(int value);
constexpr RouterMethods RouterMethods_MIN = ROUTER_METHODS_OCPP201;
constexpr RouterMethods RouterMethods_MAX = ROUTER_METHODS_NETWORK_OFFLINE;
constexpr int RouterMethods_ARRAYSIZE = RouterMethods_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RouterMethods_descriptor();
template<typename T>
inline const std::string& RouterMethods_Name(T enum_t_value) {
  static_assert(::std::is_same<T, RouterMethods>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function RouterMethods_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    RouterMethods_descriptor(), enum_t_value);
}
inline bool RouterMethods_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, RouterMethods* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<RouterMethods>(
    RouterMethods_descriptor(), name, value);
}
enum MessageType : int {
  REQUEST = 0,
  RESPONSE = 1,
  NETWORK_ONLINE = 2,
  NETWORK_OFFLINE = 3,
  MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MessageType_IsValid(int value);
constexpr MessageType MessageType_MIN = REQUEST;
constexpr MessageType MessageType_MAX = NETWORK_OFFLINE;
constexpr int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageType_descriptor();
template<typename T>
inline const std::string& MessageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MessageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MessageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MessageType_descriptor(), enum_t_value);
}
inline bool MessageType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MessageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
// ===================================================================

class RouterProtobufMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RouterProtobufMessage) */ {
 public:
  inline RouterProtobufMessage() : RouterProtobufMessage(nullptr) {}
  ~RouterProtobufMessage() override;
  explicit PROTOBUF_CONSTEXPR RouterProtobufMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RouterProtobufMessage(const RouterProtobufMessage& from);
  RouterProtobufMessage(RouterProtobufMessage&& from) noexcept
    : RouterProtobufMessage() {
    *this = ::std::move(from);
  }

  inline RouterProtobufMessage& operator=(const RouterProtobufMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline RouterProtobufMessage& operator=(RouterProtobufMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RouterProtobufMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const RouterProtobufMessage* internal_default_instance() {
    return reinterpret_cast<const RouterProtobufMessage*>(
               &_RouterProtobufMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RouterProtobufMessage& a, RouterProtobufMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(RouterProtobufMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RouterProtobufMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RouterProtobufMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RouterProtobufMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RouterProtobufMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RouterProtobufMessage& from) {
    RouterProtobufMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RouterProtobufMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RouterProtobufMessage";
  }
  protected:
  explicit RouterProtobufMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUuidFieldNumber = 1,
    kSourceFieldNumber = 4,
    kDestFieldNumber = 5,
    kDataFieldNumber = 6,
    kOcppTypeFieldNumber = 7,
    kMethodFieldNumber = 2,
    kMessageTypeFieldNumber = 3,
  };
  // string uuid = 1;
  void clear_uuid();
  const std::string& uuid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_uuid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_uuid();
  PROTOBUF_NODISCARD std::string* release_uuid();
  void set_allocated_uuid(std::string* uuid);
  private:
  const std::string& _internal_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(const std::string& value);
  std::string* _internal_mutable_uuid();
  public:

  // string source = 4;
  void clear_source();
  const std::string& source() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_source(ArgT0&& arg0, ArgT... args);
  std::string* mutable_source();
  PROTOBUF_NODISCARD std::string* release_source();
  void set_allocated_source(std::string* source);
  private:
  const std::string& _internal_source() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_source(const std::string& value);
  std::string* _internal_mutable_source();
  public:

  // string dest = 5;
  void clear_dest();
  const std::string& dest() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_dest(ArgT0&& arg0, ArgT... args);
  std::string* mutable_dest();
  PROTOBUF_NODISCARD std::string* release_dest();
  void set_allocated_dest(std::string* dest);
  private:
  const std::string& _internal_dest() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_dest(const std::string& value);
  std::string* _internal_mutable_dest();
  public:

  // string data = 6;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // optional string ocpp_type = 7;
  bool has_ocpp_type() const;
  private:
  bool _internal_has_ocpp_type() const;
  public:
  void clear_ocpp_type();
  const std::string& ocpp_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ocpp_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ocpp_type();
  PROTOBUF_NODISCARD std::string* release_ocpp_type();
  void set_allocated_ocpp_type(std::string* ocpp_type);
  private:
  const std::string& _internal_ocpp_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ocpp_type(const std::string& value);
  std::string* _internal_mutable_ocpp_type();
  public:

  // .RouterMethods method = 2;
  void clear_method();
  ::RouterMethods method() const;
  void set_method(::RouterMethods value);
  private:
  ::RouterMethods _internal_method() const;
  void _internal_set_method(::RouterMethods value);
  public:

  // .MessageType message_type = 3;
  void clear_message_type();
  ::MessageType message_type() const;
  void set_message_type(::MessageType value);
  private:
  ::MessageType _internal_message_type() const;
  void _internal_set_message_type(::MessageType value);
  public:

  // @@protoc_insertion_point(class_scope:RouterProtobufMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uuid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr source_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr dest_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ocpp_type_;
    int method_;
    int message_type_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protobufMessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RouterProtobufMessage

// string uuid = 1;
inline void RouterProtobufMessage::clear_uuid() {
  _impl_.uuid_.ClearToEmpty();
}
inline const std::string& RouterProtobufMessage::uuid() const {
  // @@protoc_insertion_point(field_get:RouterProtobufMessage.uuid)
  return _internal_uuid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RouterProtobufMessage::set_uuid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.uuid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:RouterProtobufMessage.uuid)
}
inline std::string* RouterProtobufMessage::mutable_uuid() {
  std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:RouterProtobufMessage.uuid)
  return _s;
}
inline const std::string& RouterProtobufMessage::_internal_uuid() const {
  return _impl_.uuid_.Get();
}
inline void RouterProtobufMessage::_internal_set_uuid(const std::string& value) {
  
  _impl_.uuid_.Set(value, GetArenaForAllocation());
}
inline std::string* RouterProtobufMessage::_internal_mutable_uuid() {
  
  return _impl_.uuid_.Mutable(GetArenaForAllocation());
}
inline std::string* RouterProtobufMessage::release_uuid() {
  // @@protoc_insertion_point(field_release:RouterProtobufMessage.uuid)
  return _impl_.uuid_.Release();
}
inline void RouterProtobufMessage::set_allocated_uuid(std::string* uuid) {
  if (uuid != nullptr) {
    
  } else {
    
  }
  _impl_.uuid_.SetAllocated(uuid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.uuid_.IsDefault()) {
    _impl_.uuid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:RouterProtobufMessage.uuid)
}

// .RouterMethods method = 2;
inline void RouterProtobufMessage::clear_method() {
  _impl_.method_ = 0;
}
inline ::RouterMethods RouterProtobufMessage::_internal_method() const {
  return static_cast< ::RouterMethods >(_impl_.method_);
}
inline ::RouterMethods RouterProtobufMessage::method() const {
  // @@protoc_insertion_point(field_get:RouterProtobufMessage.method)
  return _internal_method();
}
inline void RouterProtobufMessage::_internal_set_method(::RouterMethods value) {
  
  _impl_.method_ = value;
}
inline void RouterProtobufMessage::set_method(::RouterMethods value) {
  _internal_set_method(value);
  // @@protoc_insertion_point(field_set:RouterProtobufMessage.method)
}

// .MessageType message_type = 3;
inline void RouterProtobufMessage::clear_message_type() {
  _impl_.message_type_ = 0;
}
inline ::MessageType RouterProtobufMessage::_internal_message_type() const {
  return static_cast< ::MessageType >(_impl_.message_type_);
}
inline ::MessageType RouterProtobufMessage::message_type() const {
  // @@protoc_insertion_point(field_get:RouterProtobufMessage.message_type)
  return _internal_message_type();
}
inline void RouterProtobufMessage::_internal_set_message_type(::MessageType value) {
  
  _impl_.message_type_ = value;
}
inline void RouterProtobufMessage::set_message_type(::MessageType value) {
  _internal_set_message_type(value);
  // @@protoc_insertion_point(field_set:RouterProtobufMessage.message_type)
}

// string source = 4;
inline void RouterProtobufMessage::clear_source() {
  _impl_.source_.ClearToEmpty();
}
inline const std::string& RouterProtobufMessage::source() const {
  // @@protoc_insertion_point(field_get:RouterProtobufMessage.source)
  return _internal_source();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RouterProtobufMessage::set_source(ArgT0&& arg0, ArgT... args) {
 
 _impl_.source_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:RouterProtobufMessage.source)
}
inline std::string* RouterProtobufMessage::mutable_source() {
  std::string* _s = _internal_mutable_source();
  // @@protoc_insertion_point(field_mutable:RouterProtobufMessage.source)
  return _s;
}
inline const std::string& RouterProtobufMessage::_internal_source() const {
  return _impl_.source_.Get();
}
inline void RouterProtobufMessage::_internal_set_source(const std::string& value) {
  
  _impl_.source_.Set(value, GetArenaForAllocation());
}
inline std::string* RouterProtobufMessage::_internal_mutable_source() {
  
  return _impl_.source_.Mutable(GetArenaForAllocation());
}
inline std::string* RouterProtobufMessage::release_source() {
  // @@protoc_insertion_point(field_release:RouterProtobufMessage.source)
  return _impl_.source_.Release();
}
inline void RouterProtobufMessage::set_allocated_source(std::string* source) {
  if (source != nullptr) {
    
  } else {
    
  }
  _impl_.source_.SetAllocated(source, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.source_.IsDefault()) {
    _impl_.source_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:RouterProtobufMessage.source)
}

// string dest = 5;
inline void RouterProtobufMessage::clear_dest() {
  _impl_.dest_.ClearToEmpty();
}
inline const std::string& RouterProtobufMessage::dest() const {
  // @@protoc_insertion_point(field_get:RouterProtobufMessage.dest)
  return _internal_dest();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RouterProtobufMessage::set_dest(ArgT0&& arg0, ArgT... args) {
 
 _impl_.dest_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:RouterProtobufMessage.dest)
}
inline std::string* RouterProtobufMessage::mutable_dest() {
  std::string* _s = _internal_mutable_dest();
  // @@protoc_insertion_point(field_mutable:RouterProtobufMessage.dest)
  return _s;
}
inline const std::string& RouterProtobufMessage::_internal_dest() const {
  return _impl_.dest_.Get();
}
inline void RouterProtobufMessage::_internal_set_dest(const std::string& value) {
  
  _impl_.dest_.Set(value, GetArenaForAllocation());
}
inline std::string* RouterProtobufMessage::_internal_mutable_dest() {
  
  return _impl_.dest_.Mutable(GetArenaForAllocation());
}
inline std::string* RouterProtobufMessage::release_dest() {
  // @@protoc_insertion_point(field_release:RouterProtobufMessage.dest)
  return _impl_.dest_.Release();
}
inline void RouterProtobufMessage::set_allocated_dest(std::string* dest) {
  if (dest != nullptr) {
    
  } else {
    
  }
  _impl_.dest_.SetAllocated(dest, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.dest_.IsDefault()) {
    _impl_.dest_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:RouterProtobufMessage.dest)
}

// string data = 6;
inline void RouterProtobufMessage::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& RouterProtobufMessage::data() const {
  // @@protoc_insertion_point(field_get:RouterProtobufMessage.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RouterProtobufMessage::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:RouterProtobufMessage.data)
}
inline std::string* RouterProtobufMessage::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:RouterProtobufMessage.data)
  return _s;
}
inline const std::string& RouterProtobufMessage::_internal_data() const {
  return _impl_.data_.Get();
}
inline void RouterProtobufMessage::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* RouterProtobufMessage::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* RouterProtobufMessage::release_data() {
  // @@protoc_insertion_point(field_release:RouterProtobufMessage.data)
  return _impl_.data_.Release();
}
inline void RouterProtobufMessage::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:RouterProtobufMessage.data)
}

// optional string ocpp_type = 7;
inline bool RouterProtobufMessage::_internal_has_ocpp_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RouterProtobufMessage::has_ocpp_type() const {
  return _internal_has_ocpp_type();
}
inline void RouterProtobufMessage::clear_ocpp_type() {
  _impl_.ocpp_type_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RouterProtobufMessage::ocpp_type() const {
  // @@protoc_insertion_point(field_get:RouterProtobufMessage.ocpp_type)
  return _internal_ocpp_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RouterProtobufMessage::set_ocpp_type(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.ocpp_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:RouterProtobufMessage.ocpp_type)
}
inline std::string* RouterProtobufMessage::mutable_ocpp_type() {
  std::string* _s = _internal_mutable_ocpp_type();
  // @@protoc_insertion_point(field_mutable:RouterProtobufMessage.ocpp_type)
  return _s;
}
inline const std::string& RouterProtobufMessage::_internal_ocpp_type() const {
  return _impl_.ocpp_type_.Get();
}
inline void RouterProtobufMessage::_internal_set_ocpp_type(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.ocpp_type_.Set(value, GetArenaForAllocation());
}
inline std::string* RouterProtobufMessage::_internal_mutable_ocpp_type() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.ocpp_type_.Mutable(GetArenaForAllocation());
}
inline std::string* RouterProtobufMessage::release_ocpp_type() {
  // @@protoc_insertion_point(field_release:RouterProtobufMessage.ocpp_type)
  if (!_internal_has_ocpp_type()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.ocpp_type_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ocpp_type_.IsDefault()) {
    _impl_.ocpp_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void RouterProtobufMessage::set_allocated_ocpp_type(std::string* ocpp_type) {
  if (ocpp_type != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.ocpp_type_.SetAllocated(ocpp_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ocpp_type_.IsDefault()) {
    _impl_.ocpp_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:RouterProtobufMessage.ocpp_type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::RouterMethods> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::RouterMethods>() {
  return ::RouterMethods_descriptor();
}
template <> struct is_proto_enum< ::MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MessageType>() {
  return ::MessageType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protobufMessage_2eproto
